import Head from "next/head";
import styles from "../styles/Home.module.css";
import InvewComponent from "../components/InvewComponent";
import UserWindow from "../components/UserWindow";
import NonSSRWrapper from "../components/NonSSRWrapper";

export default function Home() {
  return (
    <NonSSRWrapper>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <>
            <div className={styles.bgBlock}>
              <InvewComponent />
              {/* <UserWindow /> */}
            </div>
          </>
        </main>
      </div>
    </NonSSRWrapper>
  );
}
